version: '3.7'
services:
  backend:
    container_name: backend
    image: mikethegrunt/backendv2
    ports:
      - "3000:3000"
    networks:
      - docker_network
    links:
      - mongodb
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    image: mikethegrunt/frontendv2
    ports:
      - "4200:4200"
    networks:
      - docker_network
    depends_on:
      - mongodb
      - backend
  mongodb:
    container_name: database
    image: mikethegrunt/mongo_databasev2
    ports:
      - 27017:27017
    networks:
      - docker_network
    volumes:
      - data/db:/data/db
      - data/configdb:/data/configdb
volumes:
  - data/db:/data/db
  - data/configdb:/data/configdb
networks:
  docker_network:
    driver: bridge
    ipam:
      driver: default