version: '3.7'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
      - mongoConfig:/data/configdb
volumes:
  mongoData:
  mongoConfig:
